[package]
name = "asdoc-example"
version = "0.1.0"
edition = "2021"

[dependencies]
mxmlextrema-as3parser = { path = "../../crates/parser", version = "1" }

[[example]]
name = "asdoc"
path = "example.rs"